import jsPDF from "jspdf";

interface AnalysisData {
  location_text: string;
  roof_area: number | null;
  budget: string | null;
  monthly_bill: number | null;
  panel_type: string;
  num_panels: number;
  system_capacity_kw: number;
  annual_energy_kwh: number;
  annual_ghi_kwh: number;
  created_at?: string;
}

const BRAND_ORANGE: [number, number, number] = [245, 130, 32];
const DARK_NAVY: [number, number, number] = [17, 24, 39];
const GRAY: [number, number, number] = [107, 114, 128];
const WHITE: [number, number, number] = [255, 255, 255];
const LIGHT_BG: [number, number, number] = [249, 250, 251];

export function generatePDF(analysis: AnalysisData) {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  let y = 0;

  // Header bar
  doc.setFillColor(...DARK_NAVY);
  doc.rect(0, 0, pageW, 38, "F");
  doc.setFontSize(22);
  doc.setTextColor(...WHITE);
  doc.text("SolarMap AI", 20, 18);
  doc.setFontSize(11);
  doc.setTextColor(200, 200, 200);
  doc.text("Solar Analysis Report", 20, 28);
  const dateStr = analysis.created_at
    ? new Date(analysis.created_at).toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
  doc.setFontSize(9);
  doc.text(`Generated: ${dateStr}`, pageW - 20, 28, { align: "right" });

  // Orange accent line
  doc.setFillColor(...BRAND_ORANGE);
  doc.rect(0, 38, pageW, 2, "F");

  y = 52;

  // Section 1: Location
  y = sectionHeading(doc, "1. Location Information", y);
  y = infoRow(doc, "Address / Coordinates", analysis.location_text, y);
  y = infoRow(doc, "Roof Area", analysis.roof_area ? `${analysis.roof_area} m²` : "N/A", y);
  y = infoRow(doc, "Budget Category", analysis.budget ? capitalize(analysis.budget) : "N/A", y);
  y = infoRow(doc, "Monthly Bill", analysis.monthly_bill ? `Rs. ${analysis.monthly_bill.toLocaleString()}` : "N/A", y);
  y += 8;

  // Section 2: Performance Summary
  y = sectionHeading(doc, "2. Performance Summary", y);
  const annualSavings = Math.round((analysis.annual_energy_kwh ?? 0) * 7);
  const metrics = [
    { label: "Recommended Panel",   value: analysis.panel_type },
    { label: "Number of Panels",    value: `${analysis.num_panels} panels` },
    { label: "Annual Energy",       value: `${Math.round(analysis.annual_energy_kwh).toLocaleString()} kWh` },
    { label: "Est. Annual Savings", value: `Rs. ${annualSavings.toLocaleString()}` },
  ];
  const cardW = (pageW - 50) / 2;
  metrics.forEach((m, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const cx = 20 + col * (cardW + 10);
    const cy = y + row * 26;
    doc.setFillColor(...LIGHT_BG);
    doc.roundedRect(cx, cy, cardW, 22, 3, 3, "F");
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(m.label, cx + 6, cy + 8);
    doc.setFontSize(13);
    doc.setTextColor(...DARK_NAVY);
    doc.text(m.value, cx + 6, cy + 18);
  });
  y += 62;

  // Section 3: System Details
  y = sectionHeading(doc, "3. System Details", y);
  y = infoRow(doc, "System Capacity",  `${Number(analysis.system_capacity_kw).toFixed(2)} kW`, y);
  y = infoRow(doc, "Annual GHI",       `${Math.round(analysis.annual_ghi_kwh).toLocaleString()} kWh/m²`, y);
  y += 8;

  // Section 4: Recommendation
  if (y > 240) { doc.addPage(); y = 20; }
  y = sectionHeading(doc, "4. Recommendation", y);
  doc.setFontSize(10);
  doc.setTextColor(...DARK_NAVY);
  const recText = `We recommend installing ${analysis.num_panels} ${analysis.panel_type} panels with a total system capacity of ${Number(analysis.system_capacity_kw).toFixed(2)} kW. This is projected to generate approximately ${Math.round(analysis.annual_energy_kwh).toLocaleString()} kWh of clean energy annually, resulting in estimated savings of Rs. ${annualSavings.toLocaleString()} per year.`;
  const lines = doc.splitTextToSize(recText, pageW - 40);
  doc.text(lines, 20, y);
  y += lines.length * 5 + 10;

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setDrawColor(220, 220, 220);
  doc.line(20, footerY - 4, pageW - 20, footerY - 4);
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text("Generated by SolarMap AI · Version 1.0", 20, footerY);
  doc.text("© SolarMap AI", pageW - 20, footerY, { align: "right" });

  doc.save("SolarMap-AI-Report.pdf");
}

function sectionHeading(doc: jsPDF, text: string, y: number): number {
  doc.setFontSize(13);
  doc.setTextColor(...BRAND_ORANGE);
  doc.text(text, 20, y);
  y += 3;
  doc.setDrawColor(...BRAND_ORANGE);
  doc.setLineWidth(0.5);
  doc.line(20, y, 80, y);
  return y + 8;
}

function infoRow(doc: jsPDF, label: string, value: string, y: number): number {
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(label, 20, y);
  doc.setFontSize(10);
  doc.setTextColor(...DARK_NAVY);
  doc.text(value, 90, y);
  return y + 7;
}

function capitalize(s: string): string {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : "";
}